-- require('colorbuddy').colorscheme('snazzybuddy')
-- 
-- function toggleTheme()
--     if vim.g.background == 'dark' then
--         vim.g.background = 'light'
--     else
--         vim.g.background = 'dark'
--     end
--     require('snazzybuddy').reload()
-- end
